version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: bank_campaign_api
    container_name: bank_campaign_api
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      - PYTHONUNBUFFERED=1d
